server.port=3000

# SQLite Configuration
spring.datasource.url=jdbc:sqlite:researchhub_client_A.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Initialize schema on startup
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

central.backend.url=http://localhost:8080
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
